<body>
    <div class="row">
        <div class="col-12 line-height-16" style="text-align: justify">
            <p class="text-underline"><strong><i>Informacje o warunkach przetwarzania danych osobowych:</i></strong></p>

            <p>Zgodnie z art. 13 ust. 1 i 2 rozporządzenia Parlamentu Europejskiego i Rady (UE) 2016/679 z 27.04.2016 r. w
                sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego
                przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (ogólne rozporządzenie o ochronie danych) (Dz.
                U. UE. L. z 2016 r. Nr 119, str. 1) – dalej RODO <strong>informujemy:</strong></p>

            <p>1) Administratorem Pani/Pana danych osobowych jest firma <strong>HEWALEX Sp. z o.o. Sp.k.</strong> z siedzibą w
                Czechowicach-Dziedzicach, 43-502 ul. Słowackiego 33.</p>

            <p>2) jako Administrator nie wyznaczyliśmy inspektora ochrony danych. W sprawach dotyczących przetwarzania
                danych osobowych można kontaktować się z pełnomocnikiem zarządu ds. ochrony danych osobowych, pisząc
                na adres odo@hewalex.pl, adres korespondencyjny Administratora lub osobiście w siedzibie firmy;</p>

            <p>3) Pani/Pana dane osobowe przetwarzane będą <strong>w celu ofertowania, zawarcia i wykonania umowy w ramach
                    niezbędnych czynności</strong> na podstawie art. 6 pkt 1 lit. b RODO oraz ewentualnej obrony przed roszczeniami lub
                ich dochodzenia, na podstawie art. 6 pkt 1 lit. f) RODO, do czasu przedawnienia roszczeń wynikających z
                zawartej umowy, określonego na podstawie przepisów powszechnie obowiązującego prawa oraz rozliczeń
                rachunkowych i podatkowych na podstawie art. 6 pkt 1 lit. c) RODO przez okres 5-ciu lat od daty zakończenia
                rozliczenia rocznego;</p>

            <p>4) <strong>odbiorcami</strong> Pani/Pana danych osobowych mogą być podmioty przetwarzające dane osobowe na zlecenie
                Administratora w celu realizacji umowy w tym firmy kurierskie, instalatorskie, windykacyjne, dostawcy usług IT;</p>

            <p>5) podanie danych jest dobrowolne, ale stanowi warunek zawarcia umowy. Niepodanie tych danych
                uniemożliwi jej zawarcie. Podanie danych w zakresie określonym przepisami powszechnie obowiązującego
                prawa, a w szczególności prawa podatkowego jest obowiązkowe.</p>

            <p>6) Pani/Pana dane osobowe <strong>nie będą</strong> przekazywane do państwa trzeciego/organizacji międzynarodowej;</p>

            <p>7) posiada Pani/Pan <strong>prawo dostępu do swoich danych,</strong> ich sprostowania, usunięcia, ograniczenia
                przetwarzania, a także <strong>prawo wniesienia skargi</strong> do organu nadzorczego;</p>

            <p>8) Pani/Pana dane będą przetwarzane w sposób <strong>ręczny</strong> lub <strong>automatyczny,</strong> nie będą przetwarzane w
                sposób zautomatyzowanego podejmowania decyzji w tym w formie profilowania.</p>
        </div>
    </div>
</body>
